server:
  port: 8081

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: workload-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_JWKS_URI:http://localhost:8082/oauth2/jwks}
  activemq:
    user: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health, info

messaging:
  workload-queue: gym.workload.queue
  workload-dlq: gym.workload.dlq
  workload-concurrency: 3-10