services:
  postgres:
    image: postgres:16-alpine
    container_name: gym_crm_postgres
    environment:
      POSTGRES_DB: gym_crm
      POSTGRES_USER: gym_user
      POSTGRES_PASSWORD: gym_pass
    volumes:
      - gym_crm_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gym_user -d gym_crm"]
      interval: 5s
      timeout: 5s
      retries: 5

  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    ports:
      - "8761:8761"

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    environment:
      EUREKA_URI: http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    ports:
      - "8082:8082"

  workload-service:
    build:
      context: .
      dockerfile: workload-service/Dockerfile
    environment:
      AUTH_JWKS_URI: http://auth-service:8082/oauth2/jwks
      EUREKA_URI: http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
      - auth-service
    ports:
      - "8081:8081"

  gym-service:
    build:
      context: .
      dockerfile: gym-service/Dockerfile
    environment:
      AUTH_JWKS_URI: http://auth-service:8082/oauth2/jwks
      EUREKA_URI: http://eureka-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gym_crm
    depends_on:
      postgres:
        condition: service_healthy
      eureka-server:
        condition: service_started
      auth-service:
        condition: service_started
    ports:
      - "8080:8080"
volumes:
  gym_crm_pgdata: