services:
  postgres:
    image: postgres:16-alpine
    container_name: gym_crm_postgres
    environment:
      POSTGRES_DB: gym_crm
      POSTGRES_USER: gym_user
      POSTGRES_PASSWORD: gym_pass
    volumes:
      - gym_crm_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gym_user -d gym_crm"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    environment:
      GYM_SERVICE_URL: http://gym-service:8080
    depends_on:
      - gym-service
    build:
      context: .
      dockerfile: auth-service/Dockerfile

  workload-service:
    build:
      context: .
      dockerfile: workload-service/Dockerfile
    environment:
      ACTIVEMQ_BROKER_URL: tcp://activemq:61616
      MONGODB_URI: mongodb://mongodb:27017/workload
    depends_on:
      auth-service:
        condition: service_started
      activemq:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  gym-service:
    build:
      context: .
      dockerfile: gym-service/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gym_crm
      ACTIVEMQ_BROKER_URL: tcp://activemq:61616
    depends_on:
      postgres:
        condition: service_healthy
      activemq:
        condition: service_healthy

  activemq:
    image: apache/activemq-classic:5.18.3
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      ACTIVEMQ_CONNECTION_USER: admin
      ACTIVEMQ_CONNECTION_PASSWORD: admin
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo > /dev/tcp/localhost/61616" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  gateway-service:
    build:
      context: .
      dockerfile: gateway-service/Dockerfile
    environment:
      AUTH_JWKS_URI: http://auth-service:8082/oauth2/jwks
      GYM_URI: http://gym-service:8080
      WORKLOAD_URI: http://workload-service:8081
      AUTH_URI: http://auth-service:8082
    depends_on:
      - gym-service
      - workload-service
      - auth-service
    ports:
      - "8080:8080"
  mongodb:
    image: mongo:7
    volumes:
      - gym_crm_mongodata:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 15s
      retries: 10
      start_period: 40s

volumes:
  gym_crm_pgdata:
  gym_crm_mongodata: