package org.volodymyrzganiaiko.gym.crm.system.dto;

import io.swagger.v3.oas.annotations.media.Schema;

import jakarta.validation.constraints.NotBlank;
import java.time.LocalDate;

@Schema(description = "Details required to register a trainee. Username and password are generated by the server.")
public record TraineeRegistrationRequest(
        @Schema(description = "First name of the trainee", requiredMode = Schema.RequiredMode.REQUIRED, example = "John")
        @NotBlank String firstName,

        @Schema(description = "Last name of the trainee", requiredMode = Schema.RequiredMode.REQUIRED, example = "Doe")
        @NotBlank String lastName,

        @Schema(description = "Date of birth, optional", example = "1990-05-15")
        LocalDate dateOfBirth,

        @Schema(description = "Postal address, optional", example = "Main st. 1")
        String address) {
}