package org.volodymyrzganiaiko.gym.crm.system.dto;

import io.swagger.v3.oas.annotations.media.Schema;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

@Schema(description = "Details required to register a trainer. Username and password are generated by the server.")
public record TrainerRegistrationRequest(
        @Schema(description = "First name of the trainer", requiredMode = Schema.RequiredMode.REQUIRED, example = "Jane")
        @NotBlank String firstName,

        @Schema(description = "Last name of the trainer", requiredMode = Schema.RequiredMode.REQUIRED, example = "Roe")
        @NotBlank String lastName,

        @Schema(description = "Identifier of an existing training type the trainer specializes in", requiredMode = Schema.RequiredMode.REQUIRED, example = "2")
        @NotNull Long specializationId) {
}