spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL:tcp://localhost:61616}

logging:
  level:
    org.volodymyrzganiaiko.gym.crm.system: info